name: Build

on:
  push:
    branches:
      - "master"
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'openjdk'
          cache: gradle

      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: release-candidate

      - name: Build with Gradle
        run: gradle shadowjar

      - name: Archive Jar Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ github.event.repository.name }}.jar
          path: build/libs/SFTH-Bot.jar
          retention-days: 1
