name: Build

on:
  push:
    branches:
      - "master"
    paths:
      - "src/**"

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: gradle

      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: release-candidate

      - name: Build with Gradle
        run: gradle shadowjar

      - name: Archive Jar Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: SFTHBot.jar
          path: build/libs/SFTHBot.jar
          retention-days: 1

      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.version.outputs.version }}
          tag_name: latest